### PR TITLE
NF: trace files belonging to VCS

### PR DESCRIPTION
**Pull request by yarikoptic**
Sits on top of @rbuccigrossi #58 

TODOs
- [x] make it work at all
- [x] basic testing
- [x] sources (remotes) for git repos
- [x] record current branch as well where applicable
- [ ] DataLad datasets support (those are just 'git' repos, but in direct mode might not look as such ;) )
- [ ] more tests!  currently barely covered

It also
- [x] refactors retrace a bit so you can now just specify bunch of files on your filesystem to be 'traced' in addition to the spec -- really handy for interactive "investigation"

Future TODOs is to support
- [ ] hg 
- [ ] CVS
- [ ] bzr
and refactor code accordingly

Also possibly
- [ ] extend to annotate changed files (might we want even to store diffs???)

## Questions

- For VCS types -- should we may be list only relative path names in files? then full paths should be easily reconstructable with a simple rule `if not isabs(path): fullpath = opj(pkg['path'], path)`?
- For full paths under '$HOME' -- I wonder if we should do analysis right away and convert them to use that (e.g. to make them '$HOME/blah' instead of '/home/yoh/blah' in my case)... and then record 'run' session and associate with tracking one which would contain value for HOME?

Sample output:
```shell
(git)hopa:~/proj/repronim/niceman[nf-git-trace]
$> niceman --dbg retrace ~/proj/repronim/niceman/README.md /home/yoh/deb/debs/imagezoom-ru-svn/trunk.upgraded/debian/changelog /usr/bin/fail2ban-client                                                                         2017-02-27 20:23:16,003 [INFO   ] DpkgManager: 1 packages with 1 files, and 2 other files 
2017-02-27 20:23:16,238 [INFO   ] VCSManager: 2 packages with 2 files, and 0 other files 
# NICEMAN Environment Configuration File
# This file was created by NICEMAN 0.0.1 on 2017-02-27 20:23:16.239261

# Package Origins 

origins:
- {name: apt_Debian_testing_main_0, type: apt, origin: Debian, label: Debian, component: main,
  archive: testing, site: http.debian.net}
- {name: apt_Debian_unstable_main_0, type: apt, origin: Debian, label: Debian, component: main,
  archive: unstable, site: http.debian.net}
- {name: apt_NeuroDebian_sid_main_0, type: apt, origin: NeuroDebian, archive: sid,
  date: '2017-02-22 16:10:55+00:00', component: main, site: neuro.debian.net, label: NeuroDebian}
- {name: apt__now_now_0, type: apt, origin: '', label: '', component: now, archive: now,
  site: ''}

# Packages 

packages:
- name: fail2ban
  type: dpkg
  version: 0.9.6-1
  candidate: 0.9.6-1
  size: 287264
  architecture: all
  md5: 1dd9650399499fc85f5ca033cab61d49
  sha1: ''
  sha256: 0f7c15500bb57af1a8881b013fcf720d611bfa669ba5f2d8cfc4003ce1bef1af
  source_name: fail2ban
  source_version: 0.9.6-1
  files: [/usr/bin/fail2ban-client]
  install_date: '2016-12-09 20:51:41.355989+00:00'
  version_table:
  - origins: [apt_Debian_testing_main_0, apt_Debian_testing_main_0, apt_Debian_unstable_main_0,
      apt_Debian_unstable_main_0, apt__now_now_0]
    version: 0.9.6-1
  - origins: [apt_NeuroDebian_sid_main_0, apt_NeuroDebian_sid_main_0]
    version: 0.9.6-1~nd+1
- path: /home/yoh/deb/debs/imagezoom-ru-svn/trunk.upgraded/debian
  type: svn
  revision: '1270'
  url: svn+ssh://washoe.rutgers.edu/home/yoh/.svn/debs/imagezoom/trunk/debian
  root_url: svn+ssh://washoe.rutgers.edu/home/yoh/.svn
  relative_url: ^/debs/imagezoom/trunk/debian
  uuid: 82381867-18eb-0310-98a2-9474e637aba2
  files: [/home/yoh/deb/debs/imagezoom-ru-svn/trunk.upgraded/debian/changelog]
- path: /home/yoh/proj/repronim/niceman
  type: git
  hexsha: ba729228fe3cf30f50745bf2a828befb22676688
  branch: nf-git-trace
  tracked_remote: gh-yarikoptic
  remotes:
    gh-chaselgrove: {url: 'git://github.com/chaselgrove/ReproNim'}
    gh-mjtravers: {url: 'https://github.com/mjtravers/ReproNim'}
    gh-rbuccigrossi: {url: 'git://github.com/rbuccigrossi/ReproNim'}
    gh-yarikoptic: {url: 'git@github.com:yarikoptic/ReproNim'}
    origin: {url: 'git@github.com:ReproNim/niceman'}
  files: [/home/yoh/proj/repronim/niceman/README.md]

# Other ReproZip keys (not used by NICEMAN) 

{}
```

### CODE REVIEW

**Comment by yarikoptic** [comment]
@rbuccigrossi FWIW -- just spotted that in my sample output debian origins were lacking the date... merged your #63 and with it -- worked correctly. Coolio!

**Comment by yarikoptic** [comment]
on another look @rbuccigrossi I have spotted:
```
origins: [apt_NeuroDebian_sid_main_0, apt_NeuroDebian_sid_main_0]
```
and it looks like two identical ones, right? ;)

**Comment by rbuccigrossi** [comment]
`origins: [apt_NeuroDebian_sid_main_0, apt_NeuroDebian_sid_main_0]`

Well, that's an interesting case: unless I have an error somewhere, it means that you have two different origins that differ in some aspect that we capture.  So the key questions are: What is it? and Do we care?

What does your "apt-cache policy fail2ban" look like?

**Comment by yarikoptic** [comment]
ah -- most probably it is due to two architectures I have enabled and fail2ban being of the architecture `all` (ie the same package build could be used on any of those):
```shell
$> apt-cache policy fail2ban
fail2ban:
  Installed: 0.9.6-1
  Candidate: 0.9.6-1
  Version table:
 *** 0.9.6-1 900
        900 http://http.debian.net/debian stretch/main amd64 Packages
        900 http://http.debian.net/debian stretch/main i386 Packages
        600 http://http.debian.net/debian sid/main amd64 Packages
        600 http://http.debian.net/debian sid/main i386 Packages
        100 /var/lib/dpkg/status
     0.9.6-1~nd+1 500
        500 http://neuro.debian.net/debian sid/main amd64 Packages
        500 http://neuro.debian.net/debian sid/main i386 Packages

$> grep '^deb .*http.debian' /etc/apt/sources.list                  
deb [arch=amd64,i386] http://http.debian.net/debian/ stretch main non-free contrib
deb [arch=amd64,i386] http://http.debian.net/debian/ sid main non-free contrib
deb [arch=amd64,i386 popcon=no] http://http.debian.net/debian/ experimental main non-free contrib
```
I guess to be more complete we should get architecture also into the origin signature, not only into package -- if all packages of architecture 'all'  and not a complete spec listing all involved packages, it would be hard if not impossible to deduce original architecture.

**Comment by yarikoptic** [comment]
really not sure why git on travis insists that I have not setup user configuration whenever I clearly did :-(

**Pull request merged**
