### PR TITLE
BF: dochelpers: Avoid FutureWarning about non-empty regexp match

### PR DESCRIPTION
**Pull request by kyleam**
This applies the same fix as DataLad's 8a87175b9.

### CODE REVIEW

**Comment by yarikoptic** [comment]
I wondered if we should just copy entire dochelpers.py from datalad. Note that originally I've created a branch `3rd` purpose of which is to contain those pristine copies of materials borrowed, so they could be merged into master to incorporate our changes.  Not sure if it is still applicable but you could try.

**Comment by kyleam** [comment]
> Note that originally I've created a branch 3rd purpose of which is to contain those pristine copies of materials borrowed, so they could be merged into master to incorporate our changes

Thanks for reminding me about that.  I'll give it a try.

**Comment by kyleam** [comment]
> Note that originally I've created a branch 3rd purpose

FTR, at this point origin/3rd is essentially a really old master (it contains a lot of niceman-specific commits), with one additional non-master commit on top (adding StarCluster files).  3rd-repronimed, on the other hand, looks right.

**Comment by yarikoptic** [comment]
ah, could be, I guess I might have messed up somewhere

**Comment by kyleam** [comment]
> 3rd-repronimed, on the other hand, looks right.

Well, looks better, but, as the name suggests, that's of course already repronimed a bit, so not what we're after.  But looking closer, the 3rd on your remote does look good.  I'll tag the current origin/3rd for posterity then update it to match yarikoptic/3rd, with the dochelper changes on top.

**Pull request closed without merging**
