### PR TITLE
NF: Address issue #77 by adding codename to origin

### PR DESCRIPTION
**Pull request by rbuccigrossi**
Address issue #77 by adding codename to origin

Note: This also updates the travis configuration to install python-apt 0.9.3.5, which works with Python 2 and 3.

TODOs
- [x] Add a test with a known file to ensure codename is being populated

### CODE REVIEW

**Comment by yarikoptic** [comment]
I guess at some point we should get some test for this functionality, right? ;)

**Comment by rbuccigrossi** [comment]
What would be better, 1) mocking the apt library transaction, or 2) getting it to work on Travis and using a file that everyone should have?

And it appears that I have a dependency on a more recent apt module :/

**Comment by rbuccigrossi** [comment]
Bah....  While I was able to get apt_1.1.0~beta5.tar up and running on a virtualenv in my box, on Travis I get the error unrecognized command line option '-std=c++11' while compiling.  So I'll have to explore that tomorrow.  

The older version of python-apt doesn't have codename in origin.  I could code around that, but I'd rather get newer versions up and running...

**Comment by rbuccigrossi** [comment]
Alas, the upgrade to python-apt is not working, so please do not merge.

**Comment by yarikoptic** [comment]
idea #1:  that sucks -- I am afraid making apt build might be like fighting with a windmill .  I would say:  make it conditional in the code -- if codename is not provided, just do not record it for now.
any reasonable system (travis's 12.04 is not reasonable any longer ;) ) will have more recent apt module available.  Known from which apt module version they started to report codename could help I guess.

idea #2: you are already accessing anyways Release file!  so you can just get the codename from there without relying on apt

**Comment by rbuccigrossi** [comment]
Windmills is right.  I was able to get Travis to work with G++ version 4.8, but now I'm getting missing header files in the older version of libapt-pkg-dev.

One more thing to try is to find if a version between 0.8.3 and 1.1.0 supported codename...

**Comment by rbuccigrossi** [comment]
Yay!  I got it working with apt 0.9.3.

So now I need to clean up, and actually build a test on a common file to make sure that these values are truly populated.

**Pull request merged**
