### PR TITLE
Make default=None  the default in attrib; use attrib consistently

### LINKED ISSUE #234: make our niceman/resource/base.py:attrib to default to default=None and use it throughout

### PR DESCRIPTION
**Pull request by kyleam**
Closes #234.

### CODE REVIEW

**Comment by yarikoptic** [comment]
Thank you!

**Comment by kyleam** [comment]
I guess codecov is acting up since it didn't add a report here?

**Comment by kyleam** [comment]
@yarikoptic @mjtravers any objections to these changes, particularly b836df19?

**Comment by yarikoptic** [comment]
no objections... that NOTHING was sticking out for me, but it was better than default everywhere so I think it is the way to go.  I have restarted travis build with the hope that may be it awakens codecov

**Comment by yarikoptic** [comment]
ok, I will merge before we start digging into conflict resolutions too much (about to fixup conflicts for #139 )

**Pull request merged**
